if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

file(GLOB_RECURSE RUNTIME_SOURCE_FILES LIST_DIRECTORIES false
  "${SOURCE_ROOT}/bbruntime/*.cpp"
  "${SOURCE_ROOT}/blitz3d/*.cpp"
  "${SOURCE_ROOT}/gxruntime/*.cpp"
)

list(SORT RUNTIME_SOURCE_FILES)

set(GENERATED_SYMBOL_LITERALS "")

function(append_symbol_literal literal)
  if("${literal}" STREQUAL "")
    return()
  endif()
  set(_current "${GENERATED_SYMBOL_LITERALS}")
  list(FIND _current "${literal}" _idx)
  if(_idx EQUAL -1)
    list(APPEND _current "${literal}")
    set(GENERATED_SYMBOL_LITERALS "${_current}" PARENT_SCOPE)
  endif()
endfunction()

foreach(source_file IN LISTS RUNTIME_SOURCE_FILES)
  file(STRINGS "${source_file}" runtime_lines REGEX "rtSym[ \t]*\\(|bindRuntimeSymbol[ \t]*\\(")
  foreach(runtime_line IN LISTS runtime_lines)
    string(REGEX MATCH "rtSym[ \t]*\\([ \t]*(\"([^\"\\\\]|\\\\.)*\")" rt_match "${runtime_line}")
    if(rt_match)
      append_symbol_literal("${CMAKE_MATCH_1}")
    endif()

    string(REGEX MATCH "bindRuntimeSymbol[ \t]*\\([ \t]*rtSym[ \t]*,[ \t]*(\"([^\"\\\\]|\\\\.)*\")" bind_match "${runtime_line}")
    if(bind_match)
      append_symbol_literal("${CMAKE_MATCH_1}")
    endif()
  endforeach()
endforeach()

file(WRITE "${OUTPUT_FILE}" "// Generated by generate_runtime_symbols.cmake. Do not edit.\n")
file(APPEND "${OUTPUT_FILE}" "static const char *const kGeneratedRuntimeSymbols[] = {\n")
foreach(symbol_literal IN LISTS GENERATED_SYMBOL_LITERALS)
  file(APPEND "${OUTPUT_FILE}" "  ${symbol_literal},\n")
endforeach()
file(APPEND "${OUTPUT_FILE}" "};\n")
file(APPEND "${OUTPUT_FILE}" "static const size_t kGeneratedRuntimeSymbolCount = sizeof(kGeneratedRuntimeSymbols) / sizeof(kGeneratedRuntimeSymbols[0]);\n")
