#!/usr/bin/env bash
#
# sweep_corpus.sh — compile-only regression gate for the bundled .bb corpus.
#
# Walks samples/, tutorials/, and games/ and compiles every .bb program with
# `blitzcc -c +q` (parse -> semant -> translate -> assemble; no execution, no
# graphics). This guards INTENT value #1 (drop-in source compatibility) by
# catching the case where a compiler/parser change silently stops a legacy
# program from compiling.
#
# The gate ratchets against a checked-in allowlist of files that are already
# known not to compile (scripts/corpus_compile_allowlist.txt). A file that fails
# to compile and is NOT on the allowlist fails the sweep (exit 1). An allowlisted
# file that now compiles, or that no longer exists, produces a non-fatal "stale"
# warning so the allowlist can be trimmed over time.
#
# Usage:
#   scripts/sweep_corpus.sh                 # run the gate (used by CI)
#   scripts/sweep_corpus.sh --update-allowlist   # rewrite the allowlist from the
#                                                 # current set of failures
#
# Each program is compiled from its own directory so that relative `Include`
# paths resolve exactly as they would for a normal build.

set -uo pipefail

ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALLOWLIST="${ROOTDIR}/scripts/corpus_compile_allowlist.txt"
CORPUS_DIRS=(samples tutorials games)

UPDATE_ALLOWLIST=0
if [[ "${1:-}" == "--update-allowlist" ]]; then
  UPDATE_ALLOWLIST=1
fi

# --- locate blitzcc (Unix binary preferred, Windows .exe fallback) -----------
BLITZCC_UNIX="${ROOTDIR}/bin/blitzcc"
BLITZCC_WIN="${ROOTDIR}/bin/blitzcc.exe"
if [[ -x "${BLITZCC_UNIX}" ]]; then
  BLITZCC="${BLITZCC_UNIX}"
elif [[ -f "${BLITZCC_WIN}" ]]; then
  BLITZCC="${BLITZCC_WIN}"
else
  echo "blitzcc not found in bin/; build it first (compile.bat / ./compile.sh)." >&2
  exit 1
fi

# --- load the allowlist into an associative set ------------------------------
declare -A ALLOW
declare -A ALLOW_SEEN
if [[ -f "${ALLOWLIST}" ]]; then
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%$'\r'}"                     # strip CR (CRLF-checked-out file)
    line="${line%%#*}"                       # strip trailing comments
    line="${line#"${line%%[![:space:]]*}"}"  # ltrim
    line="${line%"${line##*[![:space:]]}"}"  # rtrim
    [[ -z "${line}" ]] && continue
    ALLOW["${line}"]=1
  done < "${ALLOWLIST}"
fi

# --- sweep -------------------------------------------------------------------
total=0
passed=0
known_fail=0
new_fail=0
declare -a NEW_FAILS
declare -a NEW_FAIL_DIAGS
declare -a ALL_FAILS   # for --update-allowlist

while IFS= read -r -d '' f; do
  rel="${f#"${ROOTDIR}/"}"
  total=$((total + 1))
  dir="$(dirname "${f}")"
  base="$(basename "${f}")"

  diag="$(cd "${dir}" && "${BLITZCC}" -c +q "${base}" 2>&1)"
  rc=$?

  if [[ "${rc}" -eq 0 ]]; then
    passed=$((passed + 1))
    if [[ -n "${ALLOW["${rel}"]:-}" ]]; then
      ALLOW_SEEN["${rel}"]=1
      echo "STALE (now compiles, can drop from allowlist): ${rel}" >&2
    fi
    continue
  fi

  # compile failed
  ALL_FAILS+=("${rel}")
  first_diag="$(printf '%s\n' "${diag}" | grep -v '^$' | head -n 1)"
  if [[ -n "${ALLOW["${rel}"]:-}" ]]; then
    known_fail=$((known_fail + 1))
    ALLOW_SEEN["${rel}"]=1
  else
    new_fail=$((new_fail + 1))
    NEW_FAILS+=("${rel}")
    NEW_FAIL_DIAGS+=("${first_diag}")
  fi
done < <(for d in "${CORPUS_DIRS[@]}"; do
           [[ -d "${ROOTDIR}/${d}" ]] && find "${ROOTDIR}/${d}" -type f -name '*.bb' -print0
         done)

# --- --update-allowlist: rewrite the baseline and exit -----------------------
if [[ "${UPDATE_ALLOWLIST}" -eq 1 ]]; then
  {
    echo "# corpus_compile_allowlist.txt"
    echo "#"
    echo "# Files under samples/ tutorials/ games/ that do NOT compile today with"
    echo "# 'blitzcc -c +q'. The compile-sweep gate (scripts/sweep_corpus.sh) treats"
    echo "# these as known failures so it can ratchet: any NEW compile failure (a file"
    echo "# not listed here) fails CI. Annotate each entry with its cause and remove it"
    echo "# once the underlying issue is fixed."
    echo "#"
    echo "# Generated by: scripts/sweep_corpus.sh --update-allowlist"
    echo ""
    for rel in "${ALL_FAILS[@]}"; do
      printf '%s\n' "${rel}"
    done
  } > "${ALLOWLIST}"
  echo "Wrote ${#ALL_FAILS[@]} entries to ${ALLOWLIST}" >&2
  exit 0
fi

# --- report ------------------------------------------------------------------
# Warn about stale allowlist entries that no longer exist on disk.
for rel in "${!ALLOW[@]}"; do
  if [[ -z "${ALLOW_SEEN["${rel}"]:-}" && ! -f "${ROOTDIR}/${rel}" ]]; then
    echo "STALE (allowlisted file not found, can drop): ${rel}" >&2
  fi
done

echo "corpus compile sweep: ${total} files, ${passed} compiled, ${known_fail} known-fail (allowlisted), ${new_fail} new-fail"

if [[ "${new_fail}" -gt 0 ]]; then
  echo ""
  echo "NEW compile failures (not on the allowlist):" >&2
  for i in "${!NEW_FAILS[@]}"; do
    echo "  FAIL ${NEW_FAILS[$i]}" >&2
    echo "       ${NEW_FAIL_DIAGS[$i]}" >&2
  done
  echo "" >&2
  echo "A legacy program that used to compile no longer does. Fix the regression," >&2
  echo "or, if the breakage is intentional, add the file to ${ALLOWLIST#"${ROOTDIR}/"} with a reason." >&2
  exit 1
fi

echo "corpus compile sweep passed."
